services:
  - type: web
    name: crowdfund-platform
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
      - key: APP_JWT_SECRET
        generateValue: true
